from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Protocol


class FormRepositoryPort(Protocol):
    def list_taken_slugs(self) -> set[str]: ...

    def list_forms(self, *, offset: int, limit: int) -> tuple[list[Any], int]: ...

    def create_form(self, *, title: str, slug: str, now_epoch: int) -> Any: ...

    def get_form(self, form_id: int) -> Any: ...

    def get_form_by_slug(self, slug: str) -> Any: ...

    def update_form_metadata(self, *, form: Any, title: str, slug: str, now_epoch: int) -> Any: ...

    def delete_form(self, form: Any) -> None: ...

    def publish_form(self, *, form: Any, now_epoch: int) -> Any: ...

    def get_active_version(self, form: Any) -> Any: ...

    def replace_fields(
        self,
        *,
        form_version_id: int,
        field_inputs: list[dict[str, Any]],
        now_epoch: int,
    ) -> list[Any]: ...

    def get_fields_for_version(self, form_version_id: int) -> list[Any]: ...

    def slug_exists_for_other_form(self, slug: str, form_id: int) -> bool: ...


class SubmissionRepositoryPort(Protocol):
    def create_submission(
        self,
        *,
        form_id: int,
        form_version_id: int,
        answers: dict[str, str],
        now_epoch: int,
    ) -> Any: ...

    def list_submissions(self, *, form_id: int, offset: int, limit: int) -> tuple[list[Any], int]: ...

    def get_submission(self, *, form_id: int, submission_id: int) -> Any: ...

    def iter_submissions_for_export(self, form_id: int) -> Iterator[Any]: ...


class FormServicePort(Protocol):
    def query_list_forms(self, *, page: int, page_size: int) -> dict[str, Any]: ...

    def command_create_form(self, *, title: str, slug: str | None = None) -> dict[str, Any]: ...

    def query_form_detail(self, form_id: int) -> dict[str, Any]: ...

    def command_update_form(self, *, form_id: int, title: str, slug: str | None) -> dict[str, Any]: ...

    def command_delete_form(self, form_id: int) -> None: ...

    def command_replace_fields(self, *, form_id: int, fields: list[dict[str, Any]]) -> dict[str, Any]: ...

    def command_publish_form(self, form_id: int) -> dict[str, Any]: ...

    def query_public_form(self, slug: str) -> dict[str, Any]: ...


class SubmissionServicePort(Protocol):
    def command_submit_public(self, *, slug: str, values: dict[str, str]) -> dict[str, Any]: ...

    def query_list_submissions(self, *, form_id: int, page: int, page_size: int) -> dict[str, Any]: ...

    def query_submission_detail(self, *, form_id: int, submission_id: int) -> dict[str, Any]: ...


class ExportServicePort(Protocol):
    def stream_form_csv(self, *, form_id: int, export_version: str = "v1") -> Iterator[str]: ...
